---
- name: Config vm1
  hosts: vm1
  become: true
  tasks:
    - name: install frr
      package:
        name:
        - frr
        state: latest
    - name: enable ospfd
      become: yes
      replace:
        path: /etc/frr/daemons
        regexp: 'ospfd=no'
        replace: 'ospfd=yes'
    - name: copy zebra conf
      vars:
      copy:
        src: /vagrant/confs/zebra.conf
        dest: /etc/frr/zebra.conf
        owner: frr
        group: frr
    - name: copy ospfd conf
      vars:
        int1: vlan10@eth1
        int2: vlan30@eth1
        network1: 192.168.10.0/24
        network2: 192.168.30.0/24
      template:
        src: /vagrant/templates/ospfd.conf.j2
        dest: /etc/frr/ospfd.conf
        owner: frr
        group: frr
    - name: start and enable frr.service
      systemd:
        name: frr
        state: started
        enabled: yes
    - name: create vlan 10
      vars:
        vlan_n: 10
        eth_name: eth1
        ip: 192.168.10.10
        mask: 255.255.255.0
      template:
        src: /vagrant/templates/vlan.conf.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-vlan{{ vlan_n }}
        owner: vagrant
        group: vagrant
      notify:
        - restart network service
    - name: create vlan 30
      vars:
        vlan_n: 30
        eth_name: eth1
        ip: 192.168.30.11
        mask: 255.255.255.0
      template:
        src: /vagrant/templates/vlan.conf.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-vlan{{ vlan_n }}
        owner: vagrant
        group: vagrant
      notify:
        - restart network service
    - name: Copy eth0 
      copy:
        src: /vagrant/confs/ifcfg-eth0
        dest: /etc/sysconfig/network-scripts/ifcfg-eth0
        owner: vagrant
        group: vagrant
      notify:
        - restart network service
    - name: ip forward    
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
    - name: del def route to NAT 
      shell: ip route delete default
      args:
        warn: false
  handlers:
    - name: restart network service
      systemd:
        name: NetworkManager.service
        state: restarted