---
- name: Config Eth
  hosts: vm3
  become: true
  tasks:
    - name: install frr
      package:
        name:
        - frr
        state: latest
    - name: start and enable frr.service
      systemd:
        name: frr
        state: started
        enabled: yes
    - name: create vlan 10
      vars:
        vlan_n: 30
        eth_name: eth1
        ip: 192.168.10.10
        mask: 255.255.255.0
      template:
        src: /vagrant/templates/vlan.conf.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-vlan10
        owner: vagrant
        group: vagrant
      notify:
        - restart network service
    - name: create vlan 30
      vars:
        vlan_n: 20
        eth_name: eth1
        ip: 192.168.20.11
        mask: 255.255.255.0
      template:
        src: /vagrant/templates/vlan.conf.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-vlan{{ vlan_n }}
        owner: vagrant
        group: vagrant
      notify:
        - restart network service
    - name: Copy eth0 
      copy:
        src: /vagrant/confs/ifcfg-eth0
        dest: /etc/sysconfig/network-scripts/ifcfg-eth0
        owner: vagrant
        group: vagrant
      notify:
        - restart network service
    - name: ip forward    
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
    - name: del def route to NAT 
      shell: ip route delete default
      args:
        warn: no
  handlers:
    - name: restart network service
      systemd:
        name: NetworkManager.service
        state: restarted