---
# tasks file for master
- name: install postgres
  become: true
  tasks:
    - name: add pssql repo #for centos7 psql-14
      yum:
        name: http://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present
        validate_certs: yes
    - name: install pssql # install server
      yum:
        name: postgresql14-server
        state: latest
    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: "Initialize PostgreSQL"
      shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists
 
    - name: "Start and enable services"
      systemd:
        name: postgres
        state: started
        enabled: yes