---
- name: Playbook to configure IPA server with username/password
  hosts: ipaserver
  become: true
  collections: 
    - freeipa.ansible_freeipa
  roles:
    - role: ipaserver
      state: present
- name: Playbook to configure IPA clients with username/password
  hosts: ipaclients
  become: true
  collections: 
    - freeipa.ansible_freeipa
  roles:
    - role: ipaclient
      state: present