---
- name: install epel
  yum:
    name:
      - epel-*
    state: latest
- name: Install
  package: 
    name:
      - borgbackup
    state: latest

- name: create user borg
  user:
    name: borg
    comment: borg backup user
    create_home: yes
    force: yes
    home: /home/borg
    generate_ssh_key: yes
    #ssh_key_file: /home/borg/.ssh/id_rsa #private key
# - name: create repo folder
#   file:
#     path
- name: create borg folder
  file:
    path: /var/backup/borg
    state: directory
    owner: borg
    group: borg
- name: init borg repo
  shell: 'borg init -e none /var/backup/borg'     
  become: yes
  become_user: borg
