---
- name: "install epel"
  yum:
    name:
      - epel-*
    state: latest

- name: "Install borg"
  package: 
    name:
      - borgbackup
    state: latest

- name: "create user borg"
  user:
    name: borg
    comment: borg backup user
    create_home: yes
    force: yes
    #home: /var/backup/repos

- name: create ssh directory
  file:
    path: ~borg/.ssh
    state: directory
    mode: '700'
    owner: borg
    group: borg

- name: create borg folder
  file:
    path: /var/backup/repo
    state: directory
    owner: borg
    group: borg

- name: "Find out if borg repo is initialized"
  ansible.builtin.stat:
    path: "/var/backup/repo/client/README"
  register: borg_data 

- name: init borg repo
  shell: 'borg init -e authenticated /var/backup/repo/client'     
  become: yes
  become_user: borg
  when: not borg_data.stat.exists

- name: make folder fo share
  file:
    path: /var/share
    state: directory
    mode: '777'

- name: "nfsd: Configure exports"
  copy:
    src: exports
    dest: "/etc/exports"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: reload nfsd

- name: ensure nfs server started
  systemd:
    name: nfs-server
    state: started
    enabled: yes

# - name: "Copy backup.service"
#   copy:
#     src: '{{item}}'
#     dest: /etc/systemd/system
#   loop:
#     - borgprune.service
#     - borgprune.timer

# - name: "Enable backup every 1 min"
#   systemd:
#     name: '{{item}}'
#     state: started
#     enabled: yes
#     daemon-reload: yes
#   loop:
#     - borgprune.timer
#     - borgprune.service