---
- name: install epel
  yum:
    name:
      - epel-*
    state: latest
- name: Install
  package: 
    name:
      - borgbackup
    state: latest
- name: mount share for pub key
  mount:
    src: 192.168.10.10:/var/share
    path: /mnt
    state: mounted
    fstype: nfs
- name: gen ssh key
  user:
    name: vagrant
    generate_ssh_key: yes
- name: copy key 
  copy: 
    src: /home/vagrant/.ssh/ird_rsa.pub
    dest: /mnt