---
- name: Config Eth
  hosts: test
  become: true
  tasks:
    - name: Install needed network manager libs
      ansible.builtin.package:
        name:
          - NetworkManager-libnm
          - nm-connection-editor
          - libsemanage-python
          - policycoreutils-python
        state: present
    - name: Install NetworkManager-tui
      yum:
        name:
          - NetworkManager-tui
        state: latest
    - name: ifconfig0
      community.general.nmcli:
        conn_name: "System eth0"
        type: ethernet
        ifname: eth0
        never_default4: yes
        state: present
      notify:
        - restart network service
    - name: ifconfig1
      community.general.nmcli:
        conn_name: "System eth1"
        ifname: eth1
        type: ethernet
        ip4: 192.168.2.100/24
        gw4: 192.168.2.1
        routes4: 192.168.0.0/28 192.168.3.1, 192.168.2.64/26 192.168.3.1
        state: present
      notify:
        - restart network service
  handlers:
    - name: restart network service
      ansible.builtin.service:
        name: network
        state: restarted
